spring:
  datasource:
    url: ${DATABASE_URL:jdbc:postgresql://localhost:5432/todo}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:Pamo123}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate.jdbc.time_zone: UTC
  flyway:
    enabled: true

server:
  port: ${APP_PORT:8000}
